apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007 # Optional: specify a node port; otherwise, it's assigned automatically
  selector:
    app: flask-app
